name: gods_eye
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.3+1
  provider: ^3.0.0+1
  slide_container: ^1.1.3
  flutter_vlc_player: ^1.0.0
  back_button_interceptor: ^4.2.3
  flutter_vector_icons: ^0.2.1
  rxdart: ^0.24.0
  circular_profile_avatar: ^1.0.6
  url_launcher: ^5.4.7


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/
    - images/streams/
    - images/cameras/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Light.otf





    - family: CustomFont
      fonts:
        - asset: fonts/CustomFont.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf

    - family: back_icon
      fonts:
        - asset: fonts/back_icon.ttf

    - family: SF-Pro-Display-Bold
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.ttf


    - family: SF-Pro-Display-Regular
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.ttf

